name: Validate DayTradeSetup Notebook

on:
  push:
    paths:
      - '**DayTradeSetup.ipynb'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install nbconvert jupyter pandas numpy requests nltk MetaTrader5 tabulate
        python -m nltk.downloader vader_lexicon

    - name: Run Notebook (headless)
      run: |
        jupyter nbconvert --to notebook --execute DayTradeSetup.ipynb --output executed.ipynb
